---
- hosts: ansible_client
  gather_facts: yes
  become: true
  vars_files:
    - ./vars/defualt-ubuntu.yml
  tasks:
      - name: Set Nameserver
        include: ./dns/dns.yml

      - name: Install Docker on CentOS
        include: ./centos.yml
        when: 
          - ansible_facts['distribution'] == "CentOS"

      - name: Install Docker on Ubuntu
        include: ./ubuntu.yml
        when: 
          - ansible_facts['distribution'] == "Ubuntu"
