---
- hosts: ansible_client
  become: true
  vars_files:
    - ./vars/self_signed_certs.yml

  tasks:
       - name: Create self-signed certificate
         command: >
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "{{Key}}" -out "{{cert}}"
            -subj "/C=US/ST=New York/L=Brooklyn/O=Example Brooklyn Company/CN=examplebrooklyn.com

       - name: Write the apache default-ssl file
         ansible.builtin.template:
          src: ./files/default-ssl.j2
          dest: /etc/apache2/sites-available/default-ssl.conf

         notify:
         - Restart apache

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted     

  